#!/bin/bash

set -e
version="v1.0.4"
package=pled-"$version"

cd "$(dirname "$0")"
rm -rf "$package" "$package".zip

if [ "$1" == "clean" ]; then
    exit 0
fi

mkdir $package
cp -r pled readme.md images unlicense.md "$package"

chmod -R 777 "$package"
zip -r "$package".zip "$package"
