#!/bin/bash

echo -e "Portable Linux Executable Directory v1.0.2\nBy Alex Free\n"

if [ "$#" != 2 ]; then
  echo -e "Usage:\npled <command or full executable file path> <output directory>"
  exit 1
fi

binary_full_path=$(command -v "$1")

if [ -f "$binary_full_path" ]; then

	binary=$(basename "$1")
	if [ -e "$2" ]; then
		read -p "The directory "$2" already exists, is it ok to delete and create a new directory of this name ? (Y/n): " -n 1 -r
			if [ $REPLY = "y" ] || [ $REPLY = "Y" ]; then
				rm -r "$2"
				echo
      	else
   			echo -e "\nPLED has aborted"
				exit 0   		
   		fi   	
	fi
	mkdir "$2"
	cp "$binary_full_path" "$2"/"$binary"2
	cd "$2"
	if file --mime-type "$binary"2 | grep 'executable' > /dev/null 2>&1; then
		echo "Validated "$binary_full_path" as an executable"
	elif file --mime-type "$binary"2 | grep 'shellscript' > /dev/null 2>&1; then
      read -p "Error: "$binary_full_path" is NOT actually an executable file. It is a shell script that executes the real executable, which is somewhere else. Do you want to view the shell script "$binary_full_path"? (Y/n): " -n 1 -r
		if [ $REPLY = "y" ] || [ $REPLY = "Y" ]; then
			echo
      	cat "$binary_full_path"
      fi
      rm -rf "$2"
      exit 0
   else
   	echo "Error: "$binary_full_path" is not an executable."
	fi

	all_linked_libs=$(ldd ./"$binary"2 | grep -Po '/.*(?= \(0x)')
	loader=$(echo "$all_linked_libs" | grep ld-linux*)
	loader_name=$(basename "$loader")
 	echo "Got LD loader: "$loader_name""
	while IFS= read -r line; do
	   cp -L "$line" .
	done <<< "${all_linked_libs}"
	total_copied=$(echo "${all_linked_libs}" | wc -l)
	libs_count=$(expr $total_copied - 1)
	echo "Copied "$libs_count" shared libraries"
	echo -e "#!/bin/bash\n"'"${BASH_SOURCE%/*}"'"/"$loader_name" --library-path "'"${BASH_SOURCE%/*}"'" "'"${BASH_SOURCE%/*}"'"\"/"$binary"\"2 "'"$@"'"" > "$binary" 
	echo -e "#!/bin/bash\nenv LD_TRACE_LOADED_OBJECTS=1 "'"${BASH_SOURCE%/*}"'"/"$loader_name" --library-path "'"${BASH_SOURCE%/*}"'" "'"${BASH_SOURCE%/*}"'"\"/"$binary"\"2 '"$@"'" > "$binary"-ldd 
	chmod 775 *
else
  echo "Error: Can not find the executable file: "$1""
  exit 1
fi
