#!/bin/bash

echo -e "Portable Linux Executable Directory (PLED) v1.0.5\nBy Alex Free\n"

if [ "$#" != 2 ]; then
	echo -e "Usage:\npled <command in PATH or executable file> <output directory>"
	exit 1
fi

executable_full_path=$(command -v "$1")

if [ -f "$executable_full_path" ]; then
	executable=$(basename "$1")

	if file --mime-type "$executable_full_path" | grep 'executable' > /dev/null 2>&1; then
		echo "Validated "$executable_full_path" as an executable"
	elif file --mime-type "$executable_full_path" | grep 'shellscript' > /dev/null 2>&1; then
    	read -p "Error: "$executable_full_path" is NOT actually an executable file. It is a shell script that executes the real executable, which is somewhere else. Do you want to view the shell script "$executable_full_path"? (Y/n): " -n 1 -r
		
		if [ $REPLY = "y" ] || [ $REPLY = "Y" ]; then
			echo
      		cat "$executable_full_path"
      	fi
      	
      	exit 0
   else
   		echo "Error: "$executable_full_path" is not an executable."
		exit 1
	fi

	if [ -e "$2" ]; then
		echo "Info: "$2" is an existing directory"
	else
		mkdir "$2"
	fi

	set -e 
	executable_full_path=$(realpath "$executable_full_path")
	cp -v "$executable_full_path" "$2"/"$executable"2
	cd "$2"
	all_linked_libs=$(ldd "$executable_full_path" | grep '=>' | awk '{print $3}')
	# ldd "$executable_full_path"
	# echo "${all_linked_libs}"
	loader=$(ldd "$executable_full_path" | grep ld-linux* | awk '{print $1}')
	loader_name=$(basename "$loader")
 	echo "Got LD loader: "$loader_name""
	cp -v "$loader" .
	
	while IFS= read -r line; do
	   cp -L -v "$line" .
	done <<< "${all_linked_libs}"

	total_copied=$(echo "${all_linked_libs}" | wc -l)
	echo "Copied "$total_copied" shared libraries"
	echo -e "#!/bin/bash\n"'"${BASH_SOURCE%/*}"'"/"$loader_name" --library-path "'"${BASH_SOURCE%/*}"'" "'"${BASH_SOURCE%/*}"'"\"/"$executable"\"2 "'"$@"'"" > "$executable" 
	echo -e "#!/bin/bash\nenv LD_TRACE_LOADED_OBJECTS=1 "'"${BASH_SOURCE%/*}"'"/"$loader_name" --library-path "'"${BASH_SOURCE%/*}"'" "'"${BASH_SOURCE%/*}"'"\"/"$executable"\"2 '"$@"'" > "$executable"-ldd 
	chmod -R 777 *
else
	echo "Error: "$1" not found as a filepath or a command in your "\"\$PATH"\""
	exit 1
fi
