#!/bin/bash

echo "Portable Linux Executable Directory v1.0 by Alex Free"

if [ "$#" -eq 1 ]; then
	binary_full_path=$(command -v "$1")
else
  echo -e "PLED only accepts 1 argument\nUsage:\npled <executable filename>\npled <executable in path"
  exit 1
fi

if [ -f "$binary_full_path" ]; then

	binary=$(basename "$1")
	if [ -d "$binary"-pled ]; then
		read -p "The directory "$binary"-pled already exists, is it ok to overwrite it? (Y/n): " -n 1 -r
			if [ $REPLY = "y" ] || [ $REPLY = "Y" ]; then
				rm -r "$binary"-pled
				echo
      	else
   			echo -e "\nPLED has aborted"
				exit 0   		
   		fi   	
	fi
	mkdir "$binary"-pled
	cp "$binary_full_path" "$binary"-pled/"$binary"2
	cd "$binary"-pled
	if file --mime-type "$binary"2 | grep 'executable' > /dev/null 2>&1; then
		echo "Validated "$binary_full_path" as an executable"
	elif file --mime-type "$binary"2 | grep 'shellscript' > /dev/null 2>&1; then
      read -p "Error: "$binary_full_path" is NOT actually an executable file. It is a shell script that executes the real executable, which is somewhere else. Do you want to view the shell script "$binary_full_path"? (Y/n): " -n 1 -r
		
		if [ $REPLY = "y" ] || [ $REPLY = "Y" ]; then
			echo
      	cat "$binary_full_path"
      fi
      rm -rf "$binary"-pled
      exit 0
   else
   	echo "Error: "$binary_full_path" is not an executable."
	fi

	all_linked_libs=$(ldd ./"$binary"2 | grep -Po '/.*(?= \(0x)')
	loader=$(echo "$all_linked_libs" | grep ld-linux*)
	loader_name=$(basename "$loader")
 	echo "Got LD loader: "$loader_name""
	while IFS= read -r line; do
	   cp -L "$line" .
	done <<< "${all_linked_libs}"
	total_copied=$(echo "${all_linked_libs}" | wc -l)
	libs_count=$(expr $total_copied - 1)
	echo "Copied "$libs_count" shared libraries"
	echo -e "#!/bin/bash\ncd "'"${BASH_SOURCE%/*}"'"\n./"$loader_name" --library-path . ./\""$binary"\"2 "'"$@"'"" > "$binary" 
	echo -e "#!/bin/bash\ncd "'"${BASH_SOURCE%/*}"'"\nenv LD_TRACE_LOADED_OBJECTS=1 ./"$loader_name" --library-path . ./\""$binary"\"2 '"$@"'" > "$binary"-ldd 
	chmod 777 "$binary"
	chmod 777 "$binary"-ldd
else
  echo "Error: Can not find the file: "$1""
  exit 1
fi
